default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
test:
  <<: *default
  database: <%= ENV["DB_NAME"] %>-test
development:
  <<: *default
  database: <%= ENV["DB_NAME"] %>-dev

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>-prod
