test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

s3:
  service: S3
  endpoint: <%= ENV.fetch('S3_ENDPOINT') %>
  access_key_id: <%= ENV.fetch('S3_ACCESS_ID') %>
  secret_access_key: <%= ENV.fetch('S3_ACCESS_KEY') %>
  region: <%= ENV.fetch('S3_REGION') %>
  bucket: <%= ENV.fetch('S3_BUCKET_NAME') %>
  