version: "3.8"
name: remitano_interview_ht_nhan
services:
  cache:
    ports:
      - "6379:6379"
    image: redis:alpine
  db:
    ports:
      - "5432:5432"
    image: postgres:alpine
    environment:
      POSTGRES_DB: remitano_interview_ht_nhan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/remitano_interview_ht_nhan
      - REDIS_URL=redis://cache:6379
      - RAILS_ENV=production
    depends_on:
      - db
      - cache
  fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - VITE_BASE_URL=http://localhost:3000
      - VITE_BASE_WS_URL=ws://localhost:3000
    depends_on:
      - be


