version: "3.8"
name: remitano_interview_ht_nhan
services:
  cache:
    ports:
      - "6379:6379"
    image: redis:alpine
  db:
    ports:
      - "5432:5432"
    image: postgres:alpine
    environment:
      POSTGRES_DB: remitano_interview_ht_nhan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/remitano_interview_ht_nhan
      - REDIS_URL=redis://cache:6379
      - RAILS_ENV=production
      - GOOGLE_API_KEY=AIzaSyASTMQck-jttF8qy9rtEnt1HyEYw5AmhE8
      - ACCESS_KEY=anvyx
      - RAILS_MASTER_KEY=12c32dbc4cf3afe8986885921cc3652b
    depends_on:
      - db
      - cache
  fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=http://localhost:3000
        - VITE_BASE_WS_URL=ws://localhost:3000
    ports:
      - "3001:80"
    depends_on:
      - be


