# .rubocop.yml

require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

  Exclude:
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'app/views/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'spec/support/*'

Layout/IndentationConsistency:
  EnforcedStyle: 'indented_internal_methods'

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['^ *# ']

RSpec/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 20

Naming/BlockForwarding:
  EnforcedStyle: explicit