source 'https://rubygems.org'

ruby '3.3.3'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.1', '>= 7.1.3.3'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.5', '>= 1.5.6'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 6.4'

# Use Redis adapter to run Action Cable in production
gem 'redis', '>= 5.2'

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
gem 'kredis','>= 1.7'

gem 'connection_pool', '~> 2.4'

gem 'dotenv-rails', '~> 3.1'

gem 'will_paginate', '~> 4.0' # Pagination
# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem 'bcrypt', '~> 3.1.13'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem 'rack-cors'

gem 'annotate', '~> 3.2' # Annotates Rails/ActiveRecord Models, etc based on the database schema

gem 'activerecord_json_validator', '~> 3.0'

gem 'active_storage_validations', '~> 1.1.4'

gem 'recursive-open-struct', '~> 1.2.1' # Returns nested hash attributes as recursive OpenStructs

gem 'json-schema', '~> 4.3.0'

gem 'blueprinter', '~> 1.1.2'

gem 'multi_json', '~> 1.15'

gem 'oj', '~> 3.16' # Optimized json

gem "jwt_sessions" , '~> 3.2.2'

gem 'faker', '~> 3.4'

gem 'httparty', '~> 0.21'

gem "addressable", '~> 2.8'

gem 'ulid'

gem 'active_record_ulid', path: "./lib"

gem 'json_hash', path: "./lib"


group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'brakeman', require: false
  gem 'bullet'
  gem 'bundler-audit', require: false
  gem 'debug', platforms: %i[mri windows]
  gem 'factory_bot'
  gem 'factory_bot_rails'
  gem 'rspec-rails', '~> 6.1.0'

  gem 'fuubar'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-factory_bot'
  gem 'shoulda-matchers'
  gem 'byebug'

  gem 'parallel_tests'
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  gem "spring"
  gem 'spring-commands-rspec'
  gem 'spring-commands-parallel-tests'
  gem 'spring-commands-rubocop'
end

group :test do
  gem 'database_cleaner'
  gem 'mock_redis'
  gem 'rspec-sidekiq'
  gem 'simplecov'
  gem 'simplecov-cobertura'
  gem 'simplecov-lcov'
  gem 'timecop'
  gem 'webmock'
end
