source 'https://rubygems.org'

ruby '3.3.3'

# Rails
gem 'rails', '~> 7.2', '>= 7.2.2'

# Core
gem 'active_storage_validations', '~> 1.3'
gem 'annotate', '~> 3.2' # Annotates Rails/ActiveRecord Models, etc based on the database schema
gem 'connection_pool', '~> 2.4'
gem 'kredis', '>= 1.7' # Redis-backed data types for Rails
gem 'pg', '~> 1.5', '>= 1.5.9' # PostgreSQL database for Active Record
gem 'puma', '>= 6.4' # Puma web server for Rails
gem 'redis', '>= 5.2' # Redis adapter for Action Cable in production
gem 'dry-schema', '~> 1.13', '>= 1.13.3' # Dry schema validation
gem 'dry-validation', '~> 1.10'

# Caching and Boot Performance
gem 'bootsnap', require: false # Reduces boot times through caching
gem 'tzinfo-data', platforms: %i[windows jruby] # Time zone support on Windows

# Authentication and Authorization
gem 'bcrypt', '~> 3.1.13' # Active Model `has_secure_password` support
gem "jwt_sessions", '~> 3.2.2' # JSON Web Token (JWT) sessions

# API and JSON Utilities
gem 'blueprinter', '~> 1.1.2' # Fast JSON serialization
gem 'json-schema', '~> 5.0' # JSON schema validation
gem 'multi_json', '~> 1.15' # Multi JSON handling
gem 'oj', '~> 3.16' # Optimized JSON processing
gem 'rack-cors', '~> 2.0'  # Cross-Origin Resource Sharing (CORS) support for APIs

# Utility and Helpers
gem 'activerecord_json_validator', '~> 3.0' # JSON validator for ActiveRecord
gem 'addressable', '~> 2.8' # URI handling
gem 'dotenv-rails', '~> 3.1' # Environment variables from .env files
gem 'faker', '~> 3.4' # Fake data for testing
gem 'httparty', '~> 0.21' # HTTP client
gem 'recursive-open-struct', '~> 2.0' # Recursive OpenStructs from hashes
gem 'ulid' # Universally Unique Lexicographically Sortable Identifier
gem 'active_record_ulid', path: './lib' # ULID support for ActiveRecord
gem 'json_hash', path: './lib' # JSON hash utilities

# Pagination
gem 'pagy', '~> 9.2' # Pagination support

# Background Jobs and Asynchronous Processing
gem 'async', '~> 2.12' # Asynchronous processing
gem 'good_job', '~> 4.4' # Active Job backend for async execution with Postgres

# Swagger API Documentation
gem 'rswag-api' # Swagger API docs
gem 'rswag-ui' # Swagger UI for API docs

group :development, :test do
  # Code Quality and Static Analysis
  gem 'brakeman', require: false # Security analysis for Rails
  gem 'bundler-audit', require: false # Checks for vulnerable gems
  gem 'rubocop', require: false # Linter for Ruby code
  gem 'rubocop-factory_bot' # FactoryBot linting
  gem 'rubocop-performance', require: false # Performance-related linting
  gem 'rubocop-rails', require: false # Rails-specific linting
  gem 'rubocop-rspec', require: false # RSpec-specific linting

  # Testing
  gem 'factory_bot' # Fixtures replacement
  gem 'factory_bot_rails' # Rails integration for FactoryBot
  gem 'fuubar' # RSpec progress bar formatter
  gem 'rspec-benchmark' # RSpec matchers for benchmarking
  gem 'rspec-rails', '~> 7.1.0' # RSpec integration for Rails
  gem 'rswag-specs' # Swagger documentation support for RSpec tests
  gem 'shoulda-matchers' # Matchers for ActiveRecord, etc.
  gem 'parallel_tests' # Parallel testing

  # Debugging
  gem 'bullet' # N+1 query detection
  gem 'byebug' # Debugging console
  gem 'debug', platforms: %i[mri windows] # Debugger

  # Benchmarking
  gem 'benchmark-ips' # Iterations per second benchmarking
  gem 'benchmark-memory' # Memory benchmarking
end

group :development do
  # Spring (faster commands for big apps)
  gem 'spring'
  gem 'spring-commands-parallel-tests' # Parallel tests command
  gem 'spring-commands-rspec' # RSpec command for Spring
  gem 'spring-commands-rubocop' # RuboCop command for Spring
end

group :test do
  # Test Database and Mocking
  gem 'database_cleaner' # Clean database between tests
  gem 'mock_redis' # Mock Redis for testing

  # Test Coverage
  gem 'simplecov' # Code coverage
  gem 'simplecov-cobertura' # Cobertura format for SimpleCov
  gem 'simplecov-lcov' # LCOV format for SimpleCov

  # Time and HTTP Stubbing
  gem 'timecop' # Time travel for tests
  gem 'webmock' # HTTP request stubbing
end
